#!/bin/bash

# git_config - A script to configure the your git credentials

##### Constants
NAME="Nilay Pachauri"
EMAIL="pachauri@usc.edu"
TEXT_EDITOR=vim


##### Main

# Erase all of the previous git configurations
> ~/.gitconfig

# Generate SSH Key to Link with Github Profile
ssh-keygen -t rsa -b 2048 -C "$EMAIL"

# Global Git Configurations
git config --global user.name "$NAME"
git config --global user.email "$EMAIL"
git config --global color.ui.auto
git config --global core.editor $TEXT_EDITOR
git config --global core.autocrlf input
git config --global push.default simple

echo "Go to your SSH Key Settings on GitHub"
echo "Click on Add SSH Key"
echo "Provide a name for the key, such as $NAME Key"
echo "Copy the following key starting with \"ssh-rsa\" and ending with \"$EMAIL\""
echo ""
cat ~/.ssh/id_rsa.pub
echo ""
echo "Click Add Key"
